"""refresh tokens add column created_at

Revision ID: 2f9e58f473b3
Revises: cb4dbd55507c
Create Date: 2026-08-19 11:31:15.288888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9e58f473b3'
down_revision: Union[str, Sequence[str], None] = 'cb4dbd55507c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.String(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('refresh_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('refresh_tokens', 'created_at')
    op.drop_column('refresh_tokens', 'token_hash')
    # ### end Alembic commands ###
