"""update source data-type in items 

Revision ID: 59b3628ee5da
Revises: 8e4a3aa15ea3
Create Date: 2026-08-17 22:56:37.439310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b3628ee5da'
down_revision: Union[str, Sequence[str], None] = '8e4a3aa15ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'source',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'source',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
