"""make item body nullable

Revision ID: 99405cee081b
Revises: 75356824106d
Create Date: 2026-08-22 13:18:29.731299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99405cee081b'
down_revision: Union[str, Sequence[str], None] = '75356824106d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
